# Generated by Django 5.0.6 on 2024-05-19 07:53

import apps.general.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=30)),
                ('title_ru', models.CharField(max_length=30)),
                ('description_uz', models.CharField(max_length=300)),
                ('description_ru', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=30)),
                ('title_ru', models.CharField(max_length=30)),
                ('description_uz', models.CharField(max_length=300)),
                ('description_ru', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=30)),
                ('title_ru', models.CharField(max_length=30)),
                ('description_uz', models.CharField(max_length=300)),
                ('description_ru', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=13, validators=[apps.general.validate.phone_number_validate])),
            ],
        ),
    ]
