# Generated by Django 5.0.6 on 2024-05-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=75)),
                ('title_ru', models.CharField(blank=True, max_length=75)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_type/image')),
                ('text_uz', models.TextField(max_length=2000)),
                ('text_ru', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
