# Generated by Django 5.0.6 on 2024-05-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField(max_length=2000)),
                ('text_ru', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='about_company/image')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=75)),
                ('name_ru', models.CharField(blank=True, max_length=75)),
                ('position_uz', models.CharField(max_length=150)),
                ('position_ru', models.CharField(max_length=150)),
                ('description_uz', models.CharField(max_length=300)),
                ('description_ru', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=75)),
                ('name_ru', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='workers/image')),
                ('position_uz', models.CharField(max_length=150)),
                ('position_ru', models.CharField(max_length=150)),
                ('description_uz', models.CharField(max_length=300)),
                ('description_ru', models.CharField(max_length=300)),
            ],
        ),
    ]
