# Generated by Django 5.0.6 on 2024-05-19 07:53

import apps.general.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[apps.general.validate.phone_number_validate])),
                ('email', models.EmailField(max_length=254)),
                ('start_work_day', models.CharField(choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thu', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], max_length=3)),
                ('end_work_day', models.CharField(choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thu', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], max_length=3)),
                ('start_work_hour', models.DateTimeField()),
                ('end_work_hour', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='general/logo')),
                ('description_name_uz', models.CharField(max_length=75)),
                ('description_name_ru', models.CharField(max_length=75)),
                ('description_uz', models.TextField(max_length=1000)),
                ('description_ru', models.TextField(max_length=1000)),
                ('link_type1_uz', models.CharField(max_length=75)),
                ('link_type1_ru', models.CharField(max_length=75)),
                ('link_type2_uz', models.CharField(max_length=75)),
                ('link_type2_ru', models.CharField(max_length=75)),
            ],
        ),
    ]
