# Generated by Django 5.0.6 on 2024-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='link_type1_ru',
        ),
        migrations.RemoveField(
            model_name='general',
            name='link_type1_uz',
        ),
        migrations.RemoveField(
            model_name='general',
            name='link_type2_ru',
        ),
        migrations.RemoveField(
            model_name='general',
            name='link_type2_uz',
        ),
        migrations.AlterField(
            model_name='general',
            name='end_work_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='general',
            name='start_work_hour',
            field=models.TimeField(),
        ),
    ]
