# Generated by Django 5.0.6 on 2024-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_general_link_type1_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=75)),
                ('title_ru', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='workers/image')),
                ('description_uz', models.CharField(max_length=1000)),
                ('description_ru', models.CharField(max_length=1000)),
            ],
        ),
    ]
