# Generated by Django 5.0.6 on 2024-05-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
                ('short_description_uz', models.CharField(max_length=75)),
                ('short_description_ru', models.CharField(max_length=75)),
                ('long_description_uz', models.CharField(max_length=700)),
                ('long_description_ru', models.CharField(max_length=700)),
                ('image', models.ImageField(upload_to='main_view/image')),
            ],
        ),
    ]
